# Generated by Django 3.0.8 on 2020-07-29 09:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=100)),
                ('code', models.TextField()),
            ],
            options={
                'ordering': ['title'],
                'unique_together': {('title', 'code')},
            },
        ),
        migrations.CreateModel(
            name='Rental',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('customer', models.CharField(max_length=100)),
                ('total_rental_charge', models.DecimalField(decimal_places=4, max_digits=25)),
            ],
        ),
        migrations.CreateModel(
            name='RentalDetail',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('duration', models.IntegerField()),
                ('rental_charge', models.DecimalField(decimal_places=4, max_digits=25)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.Book')),
                ('rental', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.Rental')),
            ],
            options={
                'unique_together': {('rental', 'book')},
            },
        ),
    ]
