# Generated by Django 3.0.8 on 2020-07-29 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_rental_data'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rental',
            old_name='data',
            new_name='books_data',
        ),
    ]
