# Generated by Django 3.0.8 on 2020-07-29 21:38

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_auto_20200729_2106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rental',
            name='books_data',
            field=jsonfield.fields.JSONField(default={}),
        ),
    ]
