# Generated by Django 3.0.8 on 2020-07-29 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_auto_20200729_2138'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RentalDetail',
        ),
    ]
