# Generated by Django 3.0.8 on 2020-07-31 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_delete_rentaldetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='book_type',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='book',
            name='daily_rental_charge',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=25),
        ),
    ]
