# Generated by Django 3.0.8 on 2020-07-31 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_auto_20200731_1100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_type',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='book',
            name='daily_rental_charge',
            field=models.DecimalField(decimal_places=4, max_digits=25),
        ),
    ]
