# Generated by Django 3.0.8 on 2020-07-31 19:07

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0008_auto_20200731_1128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='daily_rental_charge',
            field=jsonfield.fields.JSONField(default={}),
        ),
    ]
